# Generated by Django 3.2.1 on 2021-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, null=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=256, verbose_name='書名')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('author', models.CharField(max_length=256, null=True, verbose_name='著者')),
                ('imprint', models.CharField(max_length=256, null=True, verbose_name='発行元出版社')),
                ('publishing_date', models.DateField(null=True, verbose_name='発売日')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name_plural': 'Collection',
            },
        ),
    ]
