# Generated by Django 3.2.1 on 2021-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='imprint',
        ),
        migrations.AddField(
            model_name='collection',
            name='publisher',
            field=models.CharField(max_length=256, null=True, verbose_name='出版社'),
        ),
    ]
